#############################################################################
# Makefile for building: ../bin/EngineMonitor
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  EngineMonitor.pro
# Template: app
# Command: /usr/bin/qt5/qmake -o Makefile EngineMonitor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQESP_NO_UDEV -D__linux__ -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iqextserialport -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = EngineMonitor1.0.0
DISTDIR = /home/root/Avionics/Cardinal-EMS/.tmp/EngineMonitor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		enginemonitor.cpp \
		bargraph.cpp \
		rpmindicator.cpp \
		cylinderheadtemperature.cpp \
		exhaustgastemperature.cpp \
		fuelmanagement.cpp \
		rdacconnect.cpp \
		nmeaconnect.cpp \
		manifoldpressure.cpp \
		PortListener.cpp \
		sensorconvert.cpp \
		circulargauge.cpp \
		alarmBox.cpp \
		textBoxGauge.cpp \
		fueldisplay.cpp \
		chtegtgauge.cpp \
		buttonbar.cpp \
		qcustomplot/qcustomplot.cpp \
		udpsocket.cpp \
		flightcalculator.cpp \
		windvector.cpp \
		hourmeter.cpp \
		spatial.cpp \
		qextserialport/qextserialport.cpp \
		qextserialport/qextserialenumerator.cpp \
		qextserialport/qextserialport_unix.cpp \
		qextserialport/qextserialenumerator_linux.cpp qrc_res.cpp \
		moc_enginemonitor.cpp \
		moc_bargraph.cpp \
		moc_rpmindicator.cpp \
		moc_cylinderheadtemperature.cpp \
		moc_exhaustgastemperature.cpp \
		moc_fuelmanagement.cpp \
		moc_rdacconnect.cpp \
		moc_nmeaconnect.cpp \
		moc_PortListener.cpp \
		moc_sensorconvert.cpp \
		moc_alarmBox.cpp \
		moc_textBoxGauge.cpp \
		moc_fueldisplay.cpp \
		moc_chtegtgauge.cpp \
		moc_buttonbar.cpp \
		moc_qcustomplot.cpp \
		moc_udpsocket.cpp \
		moc_flightcalculator.cpp \
		moc_windvector.cpp \
		moc_hourmeter.cpp \
		moc_spatial.cpp
OBJECTS       = main.o \
		enginemonitor.o \
		bargraph.o \
		rpmindicator.o \
		cylinderheadtemperature.o \
		exhaustgastemperature.o \
		fuelmanagement.o \
		rdacconnect.o \
		nmeaconnect.o \
		manifoldpressure.o \
		PortListener.o \
		sensorconvert.o \
		circulargauge.o \
		alarmBox.o \
		textBoxGauge.o \
		fueldisplay.o \
		chtegtgauge.o \
		buttonbar.o \
		qcustomplot.o \
		udpsocket.o \
		flightcalculator.o \
		windvector.o \
		hourmeter.o \
		spatial.o \
		qextserialport.o \
		qextserialenumerator.o \
		qextserialport_unix.o \
		qextserialenumerator_linux.o \
		qrc_res.o \
		moc_enginemonitor.o \
		moc_bargraph.o \
		moc_rpmindicator.o \
		moc_cylinderheadtemperature.o \
		moc_exhaustgastemperature.o \
		moc_fuelmanagement.o \
		moc_rdacconnect.o \
		moc_nmeaconnect.o \
		moc_PortListener.o \
		moc_sensorconvert.o \
		moc_alarmBox.o \
		moc_textBoxGauge.o \
		moc_fueldisplay.o \
		moc_chtegtgauge.o \
		moc_buttonbar.o \
		moc_qcustomplot.o \
		moc_udpsocket.o \
		moc_flightcalculator.o \
		moc_windvector.o \
		moc_hourmeter.o \
		moc_spatial.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		qextserialport/qextserialport.pri \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		EngineMonitor.pro enginemonitor.h \
		bargraph.h \
		rpmindicator.h \
		cylinderheadtemperature.h \
		exhaustgastemperature.h \
		fuelmanagement.h \
		rdacconnect.h \
		nmeaconnect.h \
		manifoldpressure.h \
		PortListener.h \
		sensorconvert.h \
		circulargauge.h \
		alarmBox.h \
		textBoxGauge.h \
		fueldisplay.h \
		chtegtgauge.h \
		buttonbar.h \
		qcustomplot/qcustomplot.h \
		wiringPi/wiringPi/wiringPi.h \
		udpsocket.h \
		flightcalculator.h \
		windvector.h \
		hourmeter.h \
		spatial.h \
		qextserialport/qextserialport.h \
		qextserialport/qextserialenumerator.h \
		qextserialport/qextserialport_global.h \
		qextserialport/qextserialport_p.h \
		qextserialport/qextserialenumerator_p.h main.cpp \
		enginemonitor.cpp \
		bargraph.cpp \
		rpmindicator.cpp \
		cylinderheadtemperature.cpp \
		exhaustgastemperature.cpp \
		fuelmanagement.cpp \
		rdacconnect.cpp \
		nmeaconnect.cpp \
		manifoldpressure.cpp \
		PortListener.cpp \
		sensorconvert.cpp \
		circulargauge.cpp \
		alarmBox.cpp \
		textBoxGauge.cpp \
		fueldisplay.cpp \
		chtegtgauge.cpp \
		buttonbar.cpp \
		qcustomplot/qcustomplot.cpp \
		udpsocket.cpp \
		flightcalculator.cpp \
		windvector.cpp \
		hourmeter.cpp \
		spatial.cpp \
		qextserialport/qextserialport.cpp \
		qextserialport/qextserialenumerator.cpp \
		qextserialport/qextserialport_unix.cpp \
		qextserialport/qextserialenumerator_linux.cpp
QMAKE_TARGET  = EngineMonitor
DESTDIR       = ../bin/
TARGET        = ../bin/EngineMonitor


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d ../bin/ || mkdir -p ../bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EngineMonitor.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		qextserialport/qextserialport.pri \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		EngineMonitor.pro \
		res/res.qrc \
		/usr/lib/libQt5PrintSupport.prl \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile EngineMonitor.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
qextserialport/qextserialport.pri:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
EngineMonitor.pro:
res/res.qrc:
/usr/lib/libQt5PrintSupport.prl:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EngineMonitor.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents enginemonitor.h bargraph.h rpmindicator.h cylinderheadtemperature.h exhaustgastemperature.h fuelmanagement.h rdacconnect.h nmeaconnect.h manifoldpressure.h PortListener.h sensorconvert.h circulargauge.h alarmBox.h textBoxGauge.h fueldisplay.h chtegtgauge.h buttonbar.h qcustomplot/qcustomplot.h wiringPi/wiringPi/wiringPi.h udpsocket.h flightcalculator.h windvector.h hourmeter.h spatial.h qextserialport/qextserialport.h qextserialport/qextserialenumerator.h qextserialport/qextserialport_global.h qextserialport/qextserialport_p.h qextserialport/qextserialenumerator_p.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp enginemonitor.cpp bargraph.cpp rpmindicator.cpp cylinderheadtemperature.cpp exhaustgastemperature.cpp fuelmanagement.cpp rdacconnect.cpp nmeaconnect.cpp manifoldpressure.cpp PortListener.cpp sensorconvert.cpp circulargauge.cpp alarmBox.cpp textBoxGauge.cpp fueldisplay.cpp chtegtgauge.cpp buttonbar.cpp qcustomplot/qcustomplot.cpp udpsocket.cpp flightcalculator.cpp windvector.cpp hourmeter.cpp spatial.cpp qextserialport/qextserialport.cpp qextserialport/qextserialenumerator.cpp qextserialport/qextserialport_unix.cpp qextserialport/qextserialenumerator_linux.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res/res.qrc \
		/usr/bin/qt5/rcc \
		res/splashscreen.png \
		res/gaugeSettings.ini \
		res/MS33558.ttf \
		res/settings.ini \
		res/elevator-ding.wav
	/usr/bin/qt5/rcc -name res res/res.qrc -o qrc_res.cpp

compiler_moc_header_make_all: moc_enginemonitor.cpp moc_bargraph.cpp moc_rpmindicator.cpp moc_cylinderheadtemperature.cpp moc_exhaustgastemperature.cpp moc_fuelmanagement.cpp moc_rdacconnect.cpp moc_nmeaconnect.cpp moc_PortListener.cpp moc_sensorconvert.cpp moc_alarmBox.cpp moc_textBoxGauge.cpp moc_fueldisplay.cpp moc_chtegtgauge.cpp moc_buttonbar.cpp moc_qcustomplot.cpp moc_udpsocket.cpp moc_flightcalculator.cpp moc_windvector.cpp moc_hourmeter.cpp moc_spatial.cpp moc_qextserialport.cpp moc_qextserialenumerator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_enginemonitor.cpp moc_bargraph.cpp moc_rpmindicator.cpp moc_cylinderheadtemperature.cpp moc_exhaustgastemperature.cpp moc_fuelmanagement.cpp moc_rdacconnect.cpp moc_nmeaconnect.cpp moc_PortListener.cpp moc_sensorconvert.cpp moc_alarmBox.cpp moc_textBoxGauge.cpp moc_fueldisplay.cpp moc_chtegtgauge.cpp moc_buttonbar.cpp moc_qcustomplot.cpp moc_udpsocket.cpp moc_flightcalculator.cpp moc_windvector.cpp moc_hourmeter.cpp moc_spatial.cpp moc_qextserialport.cpp moc_qextserialenumerator.cpp
moc_enginemonitor.cpp: rpmindicator.h \
		alarmBox.h \
		bargraph.h \
		fuelmanagement.h \
		manifoldpressure.h \
		textBoxGauge.h \
		fueldisplay.h \
		chtegtgauge.h \
		buttonbar.h \
		qcustomplot/qcustomplot.h \
		udpsocket.h \
		windvector.h \
		hourmeter.h \
		enginemonitor.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include enginemonitor.h -o moc_enginemonitor.cpp

moc_bargraph.cpp: bargraph.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include bargraph.h -o moc_bargraph.cpp

moc_rpmindicator.cpp: alarmBox.h \
		rpmindicator.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include rpmindicator.h -o moc_rpmindicator.cpp

moc_cylinderheadtemperature.cpp: cylinderheadtemperature.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include cylinderheadtemperature.h -o moc_cylinderheadtemperature.cpp

moc_exhaustgastemperature.cpp: exhaustgastemperature.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include exhaustgastemperature.h -o moc_exhaustgastemperature.cpp

moc_fuelmanagement.cpp: fuelmanagement.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include fuelmanagement.h -o moc_fuelmanagement.cpp

moc_rdacconnect.cpp: rdacconnect.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include rdacconnect.h -o moc_rdacconnect.cpp

moc_nmeaconnect.cpp: nmeaconnect.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include nmeaconnect.h -o moc_nmeaconnect.cpp

moc_PortListener.cpp: qextserialport/qextserialport.h \
		qextserialport/qextserialport_global.h \
		PortListener.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include PortListener.h -o moc_PortListener.cpp

moc_sensorconvert.cpp: sensorconvert.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include sensorconvert.h -o moc_sensorconvert.cpp

moc_alarmBox.cpp: alarmBox.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include alarmBox.h -o moc_alarmBox.cpp

moc_textBoxGauge.cpp: textBoxGauge.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include textBoxGauge.h -o moc_textBoxGauge.cpp

moc_fueldisplay.cpp: bargraph.h \
		fueldisplay.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include fueldisplay.h -o moc_fueldisplay.cpp

moc_chtegtgauge.cpp: chtegtgauge.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include chtegtgauge.h -o moc_chtegtgauge.cpp

moc_buttonbar.cpp: buttonbar.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include buttonbar.h -o moc_buttonbar.cpp

moc_qcustomplot.cpp: qcustomplot/qcustomplot.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include qcustomplot/qcustomplot.h -o moc_qcustomplot.cpp

moc_udpsocket.cpp: udpsocket.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include udpsocket.h -o moc_udpsocket.cpp

moc_flightcalculator.cpp: flightcalculator.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include flightcalculator.h -o moc_flightcalculator.cpp

moc_windvector.cpp: windvector.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include windvector.h -o moc_windvector.cpp

moc_hourmeter.cpp: hourmeter.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include hourmeter.h -o moc_hourmeter.cpp

moc_spatial.cpp: spatial.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include spatial.h -o moc_spatial.cpp

moc_qextserialport.cpp: qextserialport/qextserialport_global.h \
		qextserialport/qextserialport.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include qextserialport/qextserialport.h -o moc_qextserialport.cpp

moc_qextserialenumerator.cpp: qextserialport/qextserialport_global.h \
		qextserialport/qextserialenumerator.h \
		/usr/bin/qt5/moc
	/usr/bin/qt5/moc $(DEFINES) -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/root/Avionics/Cardinal-EMS -I/home/root/Avionics/Cardinal-EMS/qextserialport -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.0 -I/usr/include/c++/6.2.0/arm-poky-linux-gnueabi -I/usr/include/c++/6.2.0/backward -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include -I/usr/lib/gcc/arm-poky-linux-gnueabi/6.2.0/include-fixed -I/usr/include qextserialport/qextserialenumerator.h -o moc_qextserialenumerator.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp enginemonitor.h \
		rpmindicator.h \
		alarmBox.h \
		bargraph.h \
		fuelmanagement.h \
		manifoldpressure.h \
		textBoxGauge.h \
		fueldisplay.h \
		chtegtgauge.h \
		buttonbar.h \
		qcustomplot/qcustomplot.h \
		udpsocket.h \
		windvector.h \
		hourmeter.h \
		rdacconnect.h \
		nmeaconnect.h \
		PortListener.h \
		qextserialport/qextserialport.h \
		qextserialport/qextserialport_global.h \
		sensorconvert.h \
		flightcalculator.h \
		spatial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

enginemonitor.o: enginemonitor.cpp enginemonitor.h \
		rpmindicator.h \
		alarmBox.h \
		bargraph.h \
		fuelmanagement.h \
		manifoldpressure.h \
		textBoxGauge.h \
		fueldisplay.h \
		chtegtgauge.h \
		buttonbar.h \
		qcustomplot/qcustomplot.h \
		udpsocket.h \
		windvector.h \
		hourmeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enginemonitor.o enginemonitor.cpp

bargraph.o: bargraph.cpp bargraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bargraph.o bargraph.cpp

rpmindicator.o: rpmindicator.cpp rpmindicator.h \
		alarmBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rpmindicator.o rpmindicator.cpp

cylinderheadtemperature.o: cylinderheadtemperature.cpp cylinderheadtemperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cylinderheadtemperature.o cylinderheadtemperature.cpp

exhaustgastemperature.o: exhaustgastemperature.cpp exhaustgastemperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exhaustgastemperature.o exhaustgastemperature.cpp

fuelmanagement.o: fuelmanagement.cpp fuelmanagement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fuelmanagement.o fuelmanagement.cpp

rdacconnect.o: rdacconnect.cpp rdacconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rdacconnect.o rdacconnect.cpp

nmeaconnect.o: nmeaconnect.cpp nmeaconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nmeaconnect.o nmeaconnect.cpp

manifoldpressure.o: manifoldpressure.cpp manifoldpressure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manifoldpressure.o manifoldpressure.cpp

PortListener.o: PortListener.cpp PortListener.h \
		qextserialport/qextserialport.h \
		qextserialport/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PortListener.o PortListener.cpp

sensorconvert.o: sensorconvert.cpp sensorconvert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensorconvert.o sensorconvert.cpp

circulargauge.o: circulargauge.cpp circulargauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o circulargauge.o circulargauge.cpp

alarmBox.o: alarmBox.cpp alarmBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alarmBox.o alarmBox.cpp

textBoxGauge.o: textBoxGauge.cpp textBoxGauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textBoxGauge.o textBoxGauge.cpp

fueldisplay.o: fueldisplay.cpp fueldisplay.h \
		bargraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fueldisplay.o fueldisplay.cpp

chtegtgauge.o: chtegtgauge.cpp chtegtgauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chtegtgauge.o chtegtgauge.cpp

buttonbar.o: buttonbar.cpp buttonbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buttonbar.o buttonbar.cpp

qcustomplot.o: qcustomplot/qcustomplot.cpp qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot/qcustomplot.cpp

udpsocket.o: udpsocket.cpp udpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpsocket.o udpsocket.cpp

flightcalculator.o: flightcalculator.cpp flightcalculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flightcalculator.o flightcalculator.cpp

windvector.o: windvector.cpp windvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o windvector.o windvector.cpp

hourmeter.o: hourmeter.cpp hourmeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hourmeter.o hourmeter.cpp

spatial.o: spatial.cpp spatial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spatial.o spatial.cpp

qextserialport.o: qextserialport/qextserialport.cpp qextserialport/qextserialport.h \
		qextserialport/qextserialport_global.h \
		qextserialport/qextserialport_p.h \
		moc_qextserialport.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o qextserialport/qextserialport.cpp

qextserialenumerator.o: qextserialport/qextserialenumerator.cpp qextserialport/qextserialenumerator.h \
		qextserialport/qextserialport_global.h \
		qextserialport/qextserialenumerator_p.h \
		moc_qextserialenumerator.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator.o qextserialport/qextserialenumerator.cpp

qextserialport_unix.o: qextserialport/qextserialport_unix.cpp qextserialport/qextserialport.h \
		qextserialport/qextserialport_global.h \
		qextserialport/qextserialport_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport_unix.o qextserialport/qextserialport_unix.cpp

qextserialenumerator_linux.o: qextserialport/qextserialenumerator_linux.cpp qextserialport/qextserialenumerator.h \
		qextserialport/qextserialport_global.h \
		qextserialport/qextserialenumerator_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator_linux.o qextserialport/qextserialenumerator_linux.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_enginemonitor.o: moc_enginemonitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enginemonitor.o moc_enginemonitor.cpp

moc_bargraph.o: moc_bargraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bargraph.o moc_bargraph.cpp

moc_rpmindicator.o: moc_rpmindicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rpmindicator.o moc_rpmindicator.cpp

moc_cylinderheadtemperature.o: moc_cylinderheadtemperature.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cylinderheadtemperature.o moc_cylinderheadtemperature.cpp

moc_exhaustgastemperature.o: moc_exhaustgastemperature.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exhaustgastemperature.o moc_exhaustgastemperature.cpp

moc_fuelmanagement.o: moc_fuelmanagement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fuelmanagement.o moc_fuelmanagement.cpp

moc_rdacconnect.o: moc_rdacconnect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rdacconnect.o moc_rdacconnect.cpp

moc_nmeaconnect.o: moc_nmeaconnect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nmeaconnect.o moc_nmeaconnect.cpp

moc_PortListener.o: moc_PortListener.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PortListener.o moc_PortListener.cpp

moc_sensorconvert.o: moc_sensorconvert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensorconvert.o moc_sensorconvert.cpp

moc_alarmBox.o: moc_alarmBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alarmBox.o moc_alarmBox.cpp

moc_textBoxGauge.o: moc_textBoxGauge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textBoxGauge.o moc_textBoxGauge.cpp

moc_fueldisplay.o: moc_fueldisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fueldisplay.o moc_fueldisplay.cpp

moc_chtegtgauge.o: moc_chtegtgauge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chtegtgauge.o moc_chtegtgauge.cpp

moc_buttonbar.o: moc_buttonbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buttonbar.o moc_buttonbar.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_udpsocket.o: moc_udpsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpsocket.o moc_udpsocket.cpp

moc_flightcalculator.o: moc_flightcalculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flightcalculator.o moc_flightcalculator.cpp

moc_windvector.o: moc_windvector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_windvector.o moc_windvector.cpp

moc_hourmeter.o: moc_hourmeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hourmeter.o moc_hourmeter.cpp

moc_spatial.o: moc_spatial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spatial.o moc_spatial.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

